{
 "title": "ftps",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Containers total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "minikube" }
     ]
    }
   ]
  },
  {
   "title": "Containers running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "minikube" }
     ]
    }
   ]
  },
  {
   "title": "Containers stopped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "minikube" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "io.kubernetes.container.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "uptime_ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "io.kubernetes.container.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage (%)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "io.kubernetes.container.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "io.kubernetes.container.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "ftps" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "io.kubernetes.container.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  }
 ]
}