apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-depl
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        volumeMounts:
        - mountPath: /home/ftp-user/
          name: ftps-storage
        - mountPath: /var/log/
          name: ftps-log
        env:
          - name: PASV_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        livenessProbe:
          exec:
            command:
            - pidof
            - vsftpd
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: ftps-storage
        hostPath: 
          path: /ftps_data
          type: DirectoryOrCreate
      - name: ftps-log
        hostPath: 
          path: /ftps_log
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftp
      port: 21
      targetPort: 21
      nodePort: 21
    - name: pasv-min
      port: 21000
      targetPort: 21000
      nodePort: 21000
    - name: pasv-max
      port: 21001
      targetPort: 21001
      nodePort: 21001
